# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20160809_0908'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('name', 'author')]),
        ),
    ]
