# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 14:13
from __future__ import unicode_literals

from django.db import migrations
import words.models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20160817_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=words.models.UpperCharField(max_length=100),
        ),
    ]
